version: "3.9"

networks:
  web:
    name: web
  intercom:
    name: intercom

volumes:
  order_pg_vol:
  order_minio_vol:

services:
  traefik:
    image: "traefik:v3.5.2"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--entryPoints.web.address=:80"
      - "--api.insecure=true"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "8080:8080"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

  orderservice:
    build: .
    restart: unless-stopped
    command: ["/app/ordersystem"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orders.rule=Host(`orders.localhost`)"
      - "traefik.http.routers.orders.entrypoints=web"
      - "traefik.http.services.orders.loadbalancer.server.port=3000"
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGPORT=5432             # internal Postgres port
      - DB_HOST=order-postgres
      - S3_ACCESS_KEY_ID=root
      - S3_SECRET_ACCESS_KEY=verysecret
      - S3_ENDPOINT=order-minio:8500
    depends_on:
      - order-postgres
      - order-minio
    networks:
      - intercom
      - web

  sws:
    image: joseluisq/static-web-server:latest
    environment:
      - SERVER_PORT=80
      - SERVER_ROOT=/public
    volumes:
      - ./frontend:/public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sws.rule=Host(`localhost`)"
      - "traefik.http.routers.sws.entrypoints=web"
    networks:
      - intercom
      - web

  order-postgres:
    image: postgres:16
    restart: always
    volumes:
      - order_pg_vol:/var/lib/postgresql/data
    ports:
      - "5433:5432"             # host 5433 -> container 5432 (same as Exercise 5)
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    networks:
      - intercom

  order-minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: ["server", "/data", "--address", ":8500", "--console-address", ":9001"]
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=verysecret
    volumes:
      - order_minio_vol:/data
    ports:
      - "8500:8500"             # S3 API
      - "9001:9001"             # Web console
    networks:
      - intercom
