# todo
services:
  postgres:
    image: postgres:16-alpine
    container_name: sbd3-postgres
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d order"]
      interval: 5s
      timeout: 3s
      retries: 20

  orderservice:
    build: .
    container_name: orderservice
    environment:
      DB_HOST: postgres           # IMPORTANT: match the SERVICE name
      POSTGRES_DB: order
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_TCP_PORT: "5432"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  pgdata:
